:relfileprefix: ../../
[#0F3A8CA5A257D8EDB9BCF17110DE440D3C94EAEC]
== Class params_view

pass:v,q[A view representing query parameters in a URL]


=== Synopsis

[source,cpp,subs="verbatim,macros,-callouts"]
----
class params_view
    : public xref:reference/boost/urls/params_base.adoc[params_base];
----

Declared in file <include/boost/url/params_ref.hpp> on line 25

Defined in file <include/boost/url/params_view.hpp> on line 47

=== Member Functions
[,cols=2]
|===
|Name |Description
|xref:reference/boost/urls/params_view/2constructor-0d.adoc[`pass:v[params_view]`] |pass:v,q[Constructor]

|xref:reference/boost/urls/params_view/2constructor-091.adoc[`pass:v[params_view]`] |pass:v,q[Constructor]

|xref:reference/boost/urls/params_view/2constructor-01.adoc[`pass:v[params_view]`] |pass:v,q[Constructor]

|xref:reference/boost/urls/params_view/2constructor-09a.adoc[`pass:v[params_view]`] |pass:v,q[Constructor]

|xref:reference/boost/urls/params_view/2constructor-04.adoc[`pass:v[params_view]`] |pass:v,q[Constructor]

|xref:reference/boost/urls/params_view/operator_assign.adoc[`pass:v[operator=]`] |pass:v,q[Assignment]

|===
=== Friends
[,cols=2]
|===
|Name |Description
|xref:reference/boost/urls/params_view/8friend-07.adoc[`pass:v[url_view_base]`] |
|xref:reference/boost/urls/params_view/8friend-0d.adoc[`pass:v[params_encoded_view]`] |
|xref:reference/boost/urls/params_view/8friend-04.adoc[`pass:v[params_ref]`] |
|===

=== Description

pass:v,q[Objects of this type are used to interpret] pass:v,q[the query parameters as a bidirectional view]
pass:v,q[of key/value pairs.]
pass:v,q[The view does not retain ownership of the]
pass:v,q[elements and instead references the original]
pass:v,q[character buffer. The caller is responsible]
pass:v,q[for ensuring that the lifetime of the buffer]
pass:v,q[extends until it is no longer referenced.]

=== Example
[,cpp]
----
url_view u( "?first=John&last=Doe" );

params_view p = u.params();
----
pass:v,q[Percent escapes in strings returned when]
pass:v,q[dereferencing iterators are automatically]
pass:v,q[decoded.]

=== Iterator Invalidation
pass:v,q[Changes to the underlying character buffer]
pass:v,q[can invalidate iterators which reference it.]


