:relfileprefix: ../../
[#D2749F33898AF767C8C79F0AB737561A21EEAB6C]
== Class params_encoded_view

pass:v,q[A view representing query parameters in a URL]


=== Synopsis

[source,cpp,subs="verbatim,macros,-callouts"]
----
class params_encoded_view
    : public xref:reference/boost/urls/params_encoded_base.adoc[params_encoded_base];
----

Declared in file <include/boost/url/params_encoded_ref.hpp> on line 24

Defined in file <include/boost/url/params_encoded_view.hpp> on line 54

=== Member Functions
[,cols=2]
|===
|Name |Description
|xref:reference/boost/urls/params_encoded_view/2constructor-02.adoc[`pass:v[params_encoded_view]`] |pass:v,q[Constructor]

|xref:reference/boost/urls/params_encoded_view/2constructor-06.adoc[`pass:v[params_encoded_view]`] |pass:v,q[Constructor]

|xref:reference/boost/urls/params_encoded_view/2constructor-0c.adoc[`pass:v[params_encoded_view]`] |pass:v,q[Constructor]

|xref:reference/boost/urls/params_encoded_view/operator_assign.adoc[`pass:v[operator=]`] |pass:v,q[Assignment]

|xref:reference/boost/urls/params_encoded_view/2conversion.adoc[`pass:v[operator params_view]`] |pass:v,q[Conversion]

|===
=== Friends
[,cols=2]
|===
|Name |Description
|xref:reference/boost/urls/params_encoded_view/8friend-00.adoc[`pass:v[url_view_base]`] |
|xref:reference/boost/urls/params_encoded_view/8friend-07.adoc[`pass:v[params_view]`] |
|xref:reference/boost/urls/params_encoded_view/8friend-0c.adoc[`pass:v[params_encoded_ref]`] |
|xref:reference/boost/urls/params_encoded_view/8friend-0e.adoc[`pass:v[query_rule_t]`] |
|xref:reference/boost/urls/params_encoded_view/8friend-0b.adoc[`pass:v[parse_query]`] |
|===

=== Description

pass:v,q[Objects of this type are used to interpret] pass:v,q[the query parameters as a bidirectional view]
pass:v,q[of key/value pairs.]
pass:v,q[The view does not retain ownership of the]
pass:v,q[elements and instead references the original]
pass:v,q[character buffer. The caller is responsible]
pass:v,q[for ensuring that the lifetime of the buffer]
pass:v,q[extends until it is no longer referenced.]

=== Example
[,cpp]
----
url_view u( "?first=John&last=Doe" );

params_encoded_view p = u.encoded_params();
----
pass:v,q[Strings produced when elements are returned]
pass:v,q[have type]
xref:reference/boost/urls/param_pct_view.adoc[param_pct_view]
pass:v,q[and represent]
pass:v,q[encoded strings. Strings passed to member]
pass:v,q[functions may contain percent escapes, and]
pass:v,q[throw exceptions on invalid inputs.]

=== Iterator Invalidation
pass:v,q[Changes to the underlying character buffer]
pass:v,q[can invalidate iterators which reference it.]


