:relfileprefix: ../../../
[#9616326F0BF29671BF89E8869B255FC84C4DDDDC]
== set_host

pass:v,q[Set the host]


=== Synopsis

[source,cpp,subs="verbatim,macros,-callouts"]
----
xref:reference/boost/urls/url_base.adoc[url_base]&
set_host(string_view s);
----

Declared in file <include/boost/url/url_base.hpp> on line 921

Defined in file <src/url_base.cpp> on line 608

=== Description

pass:v,q[Depending on the contents of the passed] pass:v,q[string, this function sets the host:]

* pass:v,q[If the string is a valid IPv4 address,]
pass:v,q[then the host is set to the address.]
pass:v,q[The host type is]
xref:reference/boost/urls/host_type/ipv4.adoc[host_type::ipv4.]

* pass:v,q[If the string is a valid IPv6 address]
pass:v,q[enclosed in square brackets, then the]
pass:v,q[host is set to that address.]
pass:v,q[The host type is]
xref:reference/boost/urls/host_type/ipv6.adoc[host_type::ipv6.]

* pass:v,q[If the string is a valid IPvFuture]
pass:v,q[address enclosed in square brackets, then]
pass:v,q[the host is set to that address.]
pass:v,q[The host type is]
xref:reference/boost/urls/host_type/ipvfuture.adoc[host_type::ipvfuture.]

* pass:v,q[Otherwise, the host name is set to]
pass:v,q[the string, which may be empty.]
pass:v,q[Reserved characters in the string are]
pass:v,q[percent-escaped in the result.]
pass:v,q[The host type is]
xref:reference/boost/urls/host_type/name.adoc[host_type::name.]
pass:v,q[In all cases, when this function returns,]
pass:v,q[the URL contains an authority.]

=== Example
[,cpp]
----
assert( url( "http://www.example.com" ).set_host( "127.0.0.1" ).buffer() == "http://127.0.0.1" );
----

=== Postconditions
[,cpp]
----
this->has_authority() == true
----

=== Complexity
pass:v,q[Linear in `this->size() + s.size()`.]

=== Exception Safety
pass:v,q[Strong guarantee.]
pass:v,q[Calls to allocate may throw.]

=== BNF
[,cpp]
----
host        = IP-literal / IPv4address / reg-name

IP-literal  = "[" ( IPv6address / IPvFuture  ) "]"

reg-name    = *( unreserved / pct-encoded / "-" / ".")
----

=== Specification

* link:https://en.wikipedia.org/wiki/IPv4[IPv4 (Wikipedia)]

* link:https://datatracker.ietf.org/doc/html/rfc4291[IP Version 6 Addressing Architecture (rfc4291)]

* link:https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.2[            3.2.2. Host (rfc3986)]


