:relfileprefix: ../../../
[#76EF39FB3FAD6325296A028879F59CF9FA5E624B]
== insert

pass:v,q[Insert segments]


=== Synopsis

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<class FwdIt>
xref:reference/boost/urls/segments_encoded_base.adoc[segments_encoded_base]::xref:reference/boost/urls/segments_encoded_base/iterator.adoc[iterator]
insert(
    xref:reference/boost/urls/segments_encoded_base.adoc[segments_encoded_base]::xref:reference/boost/urls/segments_encoded_base/iterator.adoc[iterator] before,
    FwdIt first,
    FwdIt last);
----

Declared in file <include/boost/url/segments_encoded_ref.hpp> on line 505

Defined in file <include/boost/url/impl/segments_encoded_ref.hpp> on line 62

=== Description

pass:v,q[This function inserts the segments in] pass:v,q[a range before the specified position.]
pass:v,q[Reserved characters in the range are]
pass:v,q[automatically escaped.]
pass:v,q[Escapes in the range are preserved.]
pass:v,q[All iterators that are equal to]
pass:v,q[`before` or come after are invalidated.]
[NOTE]
pass:v,q[None of the character buffers referenced]
pass:v,q[by the range may overlap the character]
pass:v,q[buffer of the underlying url, or else]
pass:v,q[the behavior is undefined.]

=== Mandates
[,cpp]
----
std::is_convertible< std::iterator_traits< FwdIt >::reference_type, pct_string_view >::value == true
----

=== Complexity
pass:v,q[Linear in `std::distance( first, last ) + this->url().encoded_resource().size()`.]

=== Exception Safety
pass:v,q[Strong guarantee.]
pass:v,q[Calls to allocate may throw.]
pass:v,q[Exceptions thrown on invalid input.]


