:relfileprefix: ../../../
[#6E34942A15FE9F518F10F839265A1E9E1E178BD0]
== result

pass:v,q[The type of result returned by library functions]


=== Synopsis

[source,cpp,subs="verbatim,macros,-callouts"]
----
template<class T>
using result = result<T, error_code>;
----

Defined in file <include/boost/url/error_types.hpp> on line 280

=== Description

[NOTE]
pass:v,q[This alias is no longer supported and] pass:v,q[should not be used in new code. Please use]
pass:v,q[`system::result` instead.]
pass:v,q[This alias is included for backwards]
pass:v,q[compatibility with earlier versions of the]
pass:v,q[library.]
pass:v,q[However, it will be removed in future releases,]
pass:v,q[and using it in new code is not recommended.]
pass:v,q[Please use the updated version instead to]
pass:v,q[ensure compatibility with future versions of]
pass:v,q[the library.]

=== Declaration
[,cpp]
----
template< class T >
class result
{
public:
    //
    // Return true if the result contains an error
    //
    constexpr bool has_error() const noexcept;

    //
    // Return the error
    //
    constexpr system::error_code error() const noexcept;

    //
    // Return true if the result contains a value
    //
    constexpr bool has_value() const noexcept;
    constexpr explicit operator bool() const noexcept;

    //
    // Return the value, or throw an exception
    //
    constexpr T& value();
    constexpr T const& value() const;

    // Return the value.
    // Precondition: has_value()==true
    //
    constexpr T& operator*() noexcept;
    constexpr T* operator->() noexcept;
    constexpr T const& operator*() const noexcept;
    constexpr T const* operator->() const noexcept;

    ...more
----

=== Usage
pass:v,q[Given the function]
xref:reference/boost/urls/parse_uri.adoc[parse_uri]
pass:v,q[with this signature:]
[,cpp]
----
system::result< url_view > parse_uri( core::string_view s ) noexcept;
----
pass:v,q[The following statement captures the value in a]
pass:v,q[variable upon success, otherwise throws:]
[,cpp]
----
url_view u = parse_uri( "http://example.com/path/to/file.txt" ).value();
----
pass:v,q[This statement captures the result in a local]
pass:v,q[variable and inspects the error condition:]
[,cpp]
----
system::result< url_view > rv = parse_uri( "http://example.com/path/to/file.txt" );

if(! rv )
    std::cout << rv.error();
else
    std::cout << *rv;
----

* link:https://boost.org/libs/system/doc/html/system.html#ref_resultt_e[`boost::system::result`]


