name: fuzz

on:
  push:
  pull_request:
  schedule:
    - cron: "25 */12 * * *"
  workflow_dispatch:

jobs:
  fuzz:

    runs-on: ubuntu-latest

    steps:
      - name: Fetch head
        uses: actions/checkout@v3
        with:
          path: 'head'
      - name: Restore corpus
        uses: actions/cache@v3
        id: cache-corpus
        with:
          path: head/test/fuzz/corpus.tar
          key: corpus-${{ github.run_id }}
          restore-keys: corpus-
      - name: Unzip corpus
        if: steps.cache-corpus.outputs.cache-hit == 'true'
        working-directory: head/test/fuzz/
        run: |
          tar -vxf corpus.tar
      - name: Build boost and run fuzzer
        uses: ./head/.github/actions/build
        with:
          buildtype: 'boost'
          path: 'head'
          toolset: clang
          targets: libs/url/test/fuzz//run
      - name: Pack the corpus
        working-directory: boost-root/libs/url/test/fuzz/
        run: |
          tar cf - cmin > corpus.tar.tmp 
          mv corpus.tar.tmp "${GITHUB_WORKSPACE}"/head/test/fuzz/corpus.tar
      - name: Archive any crashes as an artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: crashes
          path: |
            boost-root/crash-*
            boost-root/leak-*
            boost-root/timeout-*
          if-no-files-found: ignore

